<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-66UG6JS3" failures="3" tests="19" name="org.example.testRunner.runners" time="132.076" errors="0" timestamp="2022-08-14T18:14:05 EET" skipped="0">
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="6.064"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="9.312"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="6.742"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="5.002">
    <failure message="expected [https://demo.nopcommerce.com/] but found [https://demo.nopcommerce.com/nokia-lumia-1020]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/] but found [https://demo.nopcommerce.com/nokia-lumia-1020]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.example.stepDefs.D06_homeSlidersStepDef.userIsNavigatedTo(D06_homeSlidersStepDef.java:20)
at ✽.user is navigated to "https://demo.nopcommerce.com/nokia-lumia-1020"(file:///C:/Users/Daniel/IdeaProjects/temp/src/main/resources/features/F06_homeSliders.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="6.423"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="10.170"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="5.509"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="9.538"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="6.181"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="5.972"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="7.991"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="6.675"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="8.027"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="6.708"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="7.636"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="5.500"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="5.090"/>
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="8.108">
    <failure message="expected [https://demo.nopcommerce.com/] but found [https://demo.nopcommerce.com/iphone-6]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/] but found [https://demo.nopcommerce.com/iphone-6]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.example.stepDefs.D06_homeSlidersStepDef.userIsNavigatedTo(D06_homeSlidersStepDef.java:20)
at ✽.user is navigated to "https://demo.nopcommerce.com/iphone-6"(file:///C:/Users/Daniel/IdeaProjects/temp/src/main/resources/features/F06_homeSliders.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="org.example.testRunner.runners" name="runScenario" time="5.428">
    <failure message="expected [https://demo.nopcommerce.com/new-online-store-is-open] but found [https://demo.nopcommerce.com/news/rss/1]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/new-online-store-is-open] but found [https://demo.nopcommerce.com/news/rss/1]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.example.pages.P03_homePage.checkNewTabUrl(P03_homePage.java:110)
at org.example.stepDefs.D07_followUsStepDef.userIsNavigatedToNewTab(D07_followUsStepDef.java:18)
at ✽.user is navigated to "https://demo.nopcommerce.com/new-online-store-is-open" new tab(file:///C:/Users/Daniel/IdeaProjects/temp/src/main/resources/features/F07_followUs.feature:17)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- org.example.testRunner.runners -->
